### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by socalcal** [drumfreak/homebridge-tuyapi-extended#1]
Sorry for the ignorance, but how do I incorporate this into homebridge?  I see code in the Basic Usage section, but I don't think that's what goes in the config.json file.  The homebridge-tuya-outlet plugin has sample config.json code, so is this what I should use?  Do I even need to use this particular plugin if I'm only using outlets or should I just stick with the homebridge-tuya-outlet plugin?  Thanks in advance for any and all assistance!

**Comment by drumfreak** [comment]
Hi there, you probably want to look at the [homebridge-tuya-powerstrip](https://github.com/drumfreak/homebridge-tuya-powerstrip) 
or [homebridge-tuya-colorlight](https://github.com/drumfreak/homebridge-tuya-colorlight) as they use this as a backend, so this is just a required module for now. However, I am going to make a platform soon to replace this.

**Comment by drumfreak** [comment]
Also beware that you're going to have to figure out how to get the localKey and so please ensure you read the documentation!

**Comment by socalcal** [comment]
Thanks for the tips!  I see how to incorporate now.  Tried to use Charles, but noticed the iOS app is $8.99.  Tried an Android device and couldn't find the right string in the packets.  Oh well.  Maybe I'll try again some other time.

**Comment by drumfreak** [comment]
I use the free 30 day trial of Charles on my macbook, I didn't realize they had an ios version. It's worth the $8.99.
