### ISSUE TITLE
Charles not showing any useful information

### ISSUE THREAD

**Issue by ncavanagh** [drumfreak/homebridge-tuyapi-extended#3]
I am using Charles 4.2.6 on Mac OS 10.13.5.  I do not see any "POST"s as shown in your screen shot, i only see "CONNECT" and there are no paths associated to any a1.tyuaus.com listings and therefore no query string to look at to get the uuid, localKey, etc.  

Is there some place else to look for these values, or is there a setting in Charles I am missing?

![screen shot 2018-07-13 at 5 02 40 pm](https://user-images.githubusercontent.com/1447467/42715926-b82d34d4-86be-11e8-8dce-9f9dbad02eb7.png)

Thank you.

**Comment by toooooobi** [comment]
You have to go to 
Proxy -> SSL Proxy Settings 

Then activate the checkbox and type in *.* to the Location.

<img width="845" alt="bildschirmfoto 2018-07-20 um 17 17 44" src="https://user-images.githubusercontent.com/41482498/43010541-fa615c5e-8c40-11e8-9b27-8809fa71b14f.png">

**Comment by ncavanagh** [comment]
Yes! that was it!  the default setup had single "*" listed for location, changing that to "*.*" gave me what I needed.  

Just in case anyone has trouble finding the localkey and UUID: the instructions if says to look for "Find the HTTPS request where a=s.m.dev.list:" I was not able to find any request with those exact paramerts.  But in looking at all the Tuyia.com POST requests I was able to find the information in the  "JSON" of the "Response" tabs of a few requests.

Again thank you toooobi I am now able to control my super inexpensive smart plugs and powerstripas via home kit!
